server:
  port: 8087

spring:
  application:
    name: idata-marketing
  
  config:
    import: "optional:file:${user.dir}/config/application-prod.yml"
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idata_ai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: idata
    password: Idata@123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    com.idataai: debug
  file:
    name: logs/idata-marketing.log
